version: '3'
services:
  couchserver:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=YOURPASSWORD
    volumes:
        - couchdb:/opt/couchdb/data
      
volumes:
  couchdb: